name: clasp

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install
        run: |
          npm init -y
          npm install clasp -g
      - name: Login
        run: |
          echo \{\"token\":\{\"access_token\":\"${{ secrets.ACCESS_TOKEN}}\",\"scope\":\"https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/script.webapp.deploy https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/logging.read https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile openid https://www.googleapis.com/auth/script.deployments\",\"token_type\":\"Bearer\",\"id_token\":\"${{ secrets.ID_TOKEN }}\",\"expiry_date\":1620870307822,\"refresh_token\":\"${{ secrets.REFRESH_TOKEN }}\"\},\"oauth2ClientSettings\":\{\"clientId\":\"${{ secrets.CLIENTID }}\",\"clientSecret\":\"${{ secrets.CLIENTSECRET }}\",\"redirectUri\":\"http://localhost\"\},\"isLocalCreds\":false\} > ~/.clasprc.json
      - name: Setup
        run: |
          echo \{\"scriptId\":\"${{ secrets.SCRIPT_ID}}\"} > ~/.clasp.json
      - name: app
        run: |
          echo \{\"timeZone\":\"Asia/Tokyo\",\"dependencies\":{}\,\"exceptionLogging\":\"STACKDRIVER\"\,\"runtimeVersion\":\"V8\"\} > ~/appsscript.json
      - name: where
        run: |
          ls ~
      - name: Deploy
        run: |
          clasp push --force
